# Generated by Django 3.0.3 on 2020-05-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20200512_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='deadline',
            field=models.DateField(blank = True , default = '2020-05-20'),
        ),
    ]
