# Generated by Django 3.0.3 on 2020-05-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_auto_20200512_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='complete',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
