# Generated by Django 3.0.3 on 2020-05-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_tasks_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='identity',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
